version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
